# Default values for device-registry.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

database:
  volume:
    storageClassName: gp2
  rootPassword: something
  database_name: device_db

mysql:
  image: mysql
  tag: "5.6"

device:
  image: "quay.io/susdas/device_image"
  tag: "1.0.0"

application:
  name: device-registry-app

replicaCount: 2

#service:
#  type: ClusterIP
#  port: 80
